merchants/controllers/SettingsController.php
<?php

namespace merchants\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\Service;
use common\models\TicketNames;

/**
 * Site controller
 */
class SettingsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionTicketNames() {
        $service = new Service();
        $data = $service->getTicketNames(1);
        $ticketNames = [];
        foreach ($data as $dt) {
            $model = new TicketNames();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $ticketNames[] = $model;
        }
        return $this->render('ticketnames', ['data' => $ticketNames]);
    }

    public function actionNewTicketName() {
        $model = new TicketNames();
        $service = new Service();
        if ($model->load(Yii::$app->request->post())) {
            $service = new Service();
            $response = (Object) $service->createTicketName($model);
            if ($response->status['code'] == 100) {
                \Yii::$app->getSession()->setFlash('success-message', "Ticket Name sucessfully created.");
                return $this->redirect(['view-ticket-name', 'id' => $response->item]);
            } else {
                $model->addError("", $response->status['message']);
            }
        }
        return $this->render('createticketname', ['model' => $model]);
    }

    public function actionViewTicketName($id) {
        $model = new TicketNames();
        $service = new Service();
        $model->setAttributes($service->getTicketName($id));
        $model->createdAt = $service->timestampToString1($model->createdAt);
        return $this->render('viewticketname', ['model' => $model]);
    }

    public function actionDeleteTicketName($id) {
        $service = new Service();
        $response = (Object) $service->ticketNameDeletion($id);
        if ($response->status['code'] == 100) {
            \Yii::$app->getSession()->setFlash('success-message', "Ticket name sucessfully deleted.");
        } else {
            \Yii::$app->getSession()->setFlash('fail-message', $response->status['message']);
        }
        return $this->redirect(['ticket-names']);
    }

}

merchants/views/settings/_data.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
?>
<?=
GridView::widget([
    'dataProvider' => new ArrayDataProvider([ 'allModels' => $data]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label'=>'Name',
            'value'=>function($data){
                return $data->name;
            }
        ],
        [
            'label'=>'Timestamp',
            'value'=>function($data){
                return $data->createdAt;
            }
        ],
        [
            'label'=>'Status',
            'value'=>function($data){
                return $data->statusId['name'];
            }
        ],
        [
            'label'=>'Created By',
            'value'=>function($data){
                return $data->createdBy['email'];
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{delete}&nbsp;&nbsp;',
            'buttons' => [
                'view' => function($url, $model) {
                    $url = Url::toRoute(['settings/view-ticket-name', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => Yii::t('yii', 'View'),]);
                },
                'delete' => function($url, $model) {
                    $url = Url::toRoute(['settings/delete-ticket-name', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, ['title' => Yii::t('yii', 'Cancel Event'),]);
                },
                    ],
                ],
            ],
        ]);
        ?>

merchants/views/settings/createticketname.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Create Ticket Name';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login" style="margin-bottom: 50px;">

    <div class="row" >
        <div id="login-container" style="float: none; ">
            <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
                <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
            <?php endif; ?>
            <?php if (Yii::$app->session->hasFlash('success-message')): ?>
                <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
            <?php endif; ?>
            <?php
            $form = ActiveForm::begin(['id' => 'create-ticketname-form']);
            if ($model->hasErrors()) {
                echo $form->errorSummary($model, ['header' => '']);
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'name', ['inputOptions' => ['placeholder' => 'name']])->textInput(['autofocus' => true])->label() ?>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Create', ['class' => 'btn btn-primary', 'name' => 'login-button', 'style' => 'width:100%;']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

merchants/views/settings/delete.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Delete Merchant Account';
$this->params['breadcrumbs'][] = "Delete/Disable [".$model->name."] Merchant Account";
?>
<div class="site-login" style="margin-bottom: 50px;">


    <div class="row" >
        <div id="login-container" style="float: none; ">
            <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
                <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
            <?php endif; ?>
            <?php if (Yii::$app->session->hasFlash('success-message')): ?>
                <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
            <?php endif; ?>
            <?php
            $form = ActiveForm::begin(['id' => 'verify-form']);
            if ($model->hasErrors()) {
                echo $form->errorSummary($model, ['header' => '']);
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'remarks', ['inputOptions' => ['placeholder' => 'remarks']])->textarea(['autofocus' => true])->label() ?>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Delete/Disable', ['class' => 'btn btn-danger', 'name' => 'login-button', 'style' => 'width:100%;']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

merchants/views/settings/pending.php
<?php
$this->title = Yii::t('app', 'Merchant Awaiting Verification');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->title ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->render('_data', ['data' => $data]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

merchants/views/settings/ticketnames.php
<?php

use yii\helpers\Html;

$this->title = Yii::t('app', 'Ticket Name List');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
            <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('success-message')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
        <?php endif; ?>
        <div class="row" >
            <div class="col-md-12 text-right">
                <p><?= Html::a('<span class="glyphicon glyphicon-plus"></span> Add Ticket Name', ['new-ticket-name'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-primary', 'title' => Yii::t('yii', 'Add ticket name'),]); ?></p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->title ?></div>
            <div class="panel-body">
                <?= $this->render('_data', ['data' => $data]) ?>
            </div>
        </div>
    </div>
</div>

merchants/views/settings/users.php
<?php
$this->title = Yii::t('app', 'Merchant Awaiting Verification');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->title ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->render('_data', ['data' => $data]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

merchants/views/settings/verify.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Approve Merchant Account';
$this->params['breadcrumbs'][] = "Approve [".$model->name."] Merchant Account";
?>
<div class="site-login" style="margin-bottom: 50px;">


    <div class="row" >
        <div id="login-container" style="float: none; ">
            <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
                <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
            <?php endif; ?>
            <?php if (Yii::$app->session->hasFlash('success-message')): ?>
                <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
            <?php endif; ?>
            <?php
            $form = ActiveForm::begin(['id' => 'verify-form']);
            if ($model->hasErrors()) {
                echo $form->errorSummary($model, ['header' => '']);
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'remarks', ['inputOptions' => ['placeholder' => 'remarks']])->textarea(['autofocus' => true])->label() ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'walletKeyOne', ['inputOptions' => ['placeholder' => 'consumer key']])->textInput()->label() ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'walletKeyTwo', ['inputOptions' => ['placeholder' => 'consumer secret key']])->textInput()->label() ?>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Verify', ['class' => 'btn btn-success', 'name' => 'login-button', 'style' => 'width:100%;']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

merchants/views/settings/viewticketname.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Ticket Name');
$this->params['breadcrumbs'][] = $this->title;
                    $url = Url::toRoute(['delete-ticket-name', 'id' => $model->id]);
?>
<div class="row members-index">
    <div class="col-md-12">
        <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
            <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('success-message')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
        <?php endif; ?>
        <div class="row" >
            <div class="col-md-12 text-right">
                <p>
                    <?= Html::a('<span class="glyphicon glyphicon-list"></span> List', ['ticket-names'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-info', 'title' => Yii::t('yii', 'list ticket names'),]); ?>
                    <?= Html::a('<span class="glyphicon glyphicon-plus"></span> Add', ['new-ticket-name'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-primary', 'title' => Yii::t('yii', 'Add ticket name'),]); ?>
                    <?= Html::a('<span class="glyphicon glyphicon-remove"></span> Delete', $url, ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-danger', 'title' => Yii::t('yii', 'delete ticket names'),]); ?>
                </p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->title . " : " . $model->name ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-7">
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                                <th>:</th>
                                <td><?= $model->name ?></td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <th>:</th>
                                <td><?= $model->statusId['name'] ?></td>
                            </tr>
                            <tr>
                                <th>Timestamp</th>
                                <th>:</th>
                                <td><?= $model->createdAt ?></td>
                            </tr>
                            <tr>
                                <th>Created By</th>
                                <th>:</th>
                                <td><?= $model->createdBy['email'] ?></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>