administrator/controllers/EventsController.php
<?php

namespace administrator\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\Service;
use common\models\Events;
use common\models\EventTickets;
use common\models\EventGallery;
use common\models\EventSponsor;
/**
 * Site controller
 */
class EventsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $service = new Service();
        $data = $service->getEvents();
        $events = [];
        foreach ($data as $dt) {
            $model = new Events();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $events[] = $model;
        }
        return $this->render('index', ['data' => $events]);
    }

    public function actionPending() {
        $service = new Service();
        $data = $service->getEvents(7);
        $events = [];
        foreach ($data as $dt) {
            $model = new Events();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $events[] = $model;
        }
        return $this->render('pending', ['data' => $events]);
    }

    public function actionActive() {
        $service = new Service();
        $data = $service->getActiveEvents();
        $events = [];
        foreach ($data as $dt) {
            $model = new Events();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $events[] = $model;
        }
        return $this->render('active', ['data' => $events]);
    }

    public function actionPublish($id) {
        $model = new Events();
        $service = new Service();
        $eventDetails = $service->getEventComprehensive($id);
        $model->setAttributes($eventDetails['event']);
        if ($model->load(Yii::$app->request->post())) {
            $service = new Service();
            $response = (Object) $service->publishEvent($model->id, $model->commission);
            if ($response->status['code'] == 100) {
                \Yii::$app->getSession()->setFlash('success-message', "Event sucessfully published.");
                return $this->redirect(['view', 'id' => $id]);
            } else {
                $model->addError("", $response->status['message']);
            }
        }
        return $this->render('publish', ['model' => $model]);
    }

    public function actionCancel($id) {
        $model = new Events();
        $service = new Service();
        $eventDetails = $service->getEventComprehensive($id);
        $model->setAttributes($eventDetails['event']);
        if ($model->load(Yii::$app->request->post())) {
            $service = new Service();
            $response = (Object) $service->cancelEvent($model->id, $model->commission);
            if ($response->status['code'] == 100) {
                \Yii::$app->getSession()->setFlash('success-message', "Event sucessfully cancelled.");
                return $this->redirect(['view', 'id' => $id]);
            } else {
                $model->addError("", $response->status['message']);
            }
        }
        return $this->render('cancel', ['model' => $model]);
    }

    public function actionView($id) {
        $model = new Events();
        $service = new Service();
        $eventDetails = $service->getEventComprehensive($id);
        $eventTickets = $eventGalleries = $eventSponsors = [];
        $model->setAttributes($eventDetails['event']);
        foreach ($eventDetails['tickets'] as $eventTicket) {
            $ticketsModel = new EventTickets();
            $ticketsModel->setAttributes($eventTicket);
            $eventTickets[] = $ticketsModel;
        }

        foreach ($eventDetails['gallery'] as $data) {
            $dataModel = new EventGallery();
            $dataModel->setAttributes($data);
            $eventGalleries[] = $dataModel;
        }

        foreach ($eventDetails['sponsors'] as $data) {
            $dataModel = new EventSponsor();
            $dataModel->setAttributes($data);
            $eventSponsors[] = $dataModel;
        }
        return $this->render('view', [
                    'model' => $model,
                    'tickettiers' => $eventTickets,
                    'sponsors' => $eventSponsors,
                    'gallery' => $eventGalleries,
                    'visibility' => false,
        ]);
    }

}

administrator/views/events/_data.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
?>
<?=
GridView::widget([
    'dataProvider' => new ArrayDataProvider([ 'allModels' => $data]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label'=>'Name',
            'value'=>function($data){
                return $data->name;
            }
        ],
        [
            'label'=>'Start Date',
            'value'=>function($data){
                return $data->startDate." ".$data->startTime;
            }
        ],
        [
            'label'=>'End Date',
            'value'=>function($data){
                return $data->endDate." ".$data->endTime;
            }
        ],
        [
            'label'=>'Merchant',
            'value'=>function($data){
                return $data->merchantId['businessName'];
            }
        ],
        [
            'label'=>'Status',
            'value'=>function($data){
                return $data->statusId['name'];
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{publish}&nbsp;&nbsp;{cancel}&nbsp;&nbsp;',
            'buttons' => [
                'view' => function($url, $model) {
                    $url = Url::toRoute(['events/view', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => Yii::t('yii', 'View'),]);
                },
                'publish' => function($url, $model) {
                    $url = Url::toRoute(['events/publish', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, ['title' => Yii::t('yii', 'Publish'), 'class'=>$model->statusId['id'] == 10 ? "disable-merchant-verification" : "enable-merchant-verification"]);
                },
                'cancel' => function($url, $model) {
                    $url = Url::toRoute(['events/cancel', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, ['title' => Yii::t('yii', 'Cancel')]);
                },
                    ],
                ],
            ],
        ]);
        ?>

administrator/views/events/_tickets.php
<?php

use yii\data\ArrayDataProvider;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
if (!isset($visibility)) {
    $visibility = true;
}
?>
<?=

GridView::widget([
    'dataProvider' => new ArrayDataProvider(['allModels' => $tickets]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Ticket Type',
            'value' => function($data) {
                return $data->ticketTypeId['name'];
            }
        ],
        [
            'label' => 'Ticket Name',
            'value' => function($data) {
                return $data->ticketNameId['name'];
            }
        ],
        [
            'label' => 'Price',
            'value' => function($data) {
                return number_format($data->price);
            }
        ],
        [
            'label' => 'Quantity',
            'value' => function($data) {
                return number_format($data->ticketQuantity);
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}&nbsp;&nbsp;',
            'visible' => $visibility,
            'buttons' => [
                'delete' => function($url, $model) {
                    $url = Url::toRoute(['events/delete-ticket-tier', 'id' => $model->id, 'eventsId' => $model->eventsId['id']]);
                    return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['data-value' => '#ticket-details-success-message', 'data-div' => '#ticket-tier-details', 'data-whatever' => $url, 'data-toggle' => "modal", 'data-target' => "#DeleteInnerReloadModal", 'title' => Yii::t('yii', 'Delete'),]);
                },
            ],
        ],
    ],
]);
?>

administrator/views/events/active.php
<?php
$this->title = Yii::t('app', 'Active Events List');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
            <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('success-message')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
        <?php endif; ?>
        <div class="panel panel-default">
            <div class="panel-heading">Events List</div>
            <div class="panel-body grid-font-formating">
                <?= $this->render('_data', ['data' => $data]) ?>
            </div>
        </div>
    </div>
</div>

administrator/views/events/cancel.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Cancel Event';
$this->params['breadcrumbs'][] = "Cancel [" . $model->name . "]";
?>
<div class="site-login" style="margin-bottom: 50px;">
    <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
        <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
    <?php endif; ?>
    <?php if (Yii::$app->session->hasFlash('success-message')): ?>
        <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-12 text-right">
            <p style="border-bottom: 1px solid #f5f5f5; padding-bottom: 5px;">
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> Active Events List', ['active'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-success', 'title' => Yii::t('yii', 'Update Event'),]); ?>
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> Awaiting Publication List', ['pending'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-primary', 'title' => Yii::t('yii', 'Update Event'),]); ?>
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> Events List', ['index'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-info', 'title' => Yii::t('yii', 'Update Event'),]); ?>
            </p>
        </div>
    </div>
    <div class="row" >
        <div id="login-container" style="float: none; ">
            <?php
            $form = ActiveForm::begin(['id' => 'publish-form']);
            if ($model->hasErrors()) {
                echo $form->errorSummary($model, ['header' => '']);
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'remarks', ['inputOptions' => ['placeholder' => 'remarks']])->textarea(['autofocus' => true])->label() ?>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Cancel Event', ['class' => 'btn btn-danger', 'name' => 'login-button', 'style' => 'width:100%;']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

administrator/views/events/index.php
<?php
$this->title = Yii::t('app', 'Events List');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
            <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('success-message')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
        <?php endif; ?>
        <div class="panel panel-default">
            <div class="panel-heading">Events List</div>
            <div class="panel-body grid-font-formating">
                <?= $this->render('_data', ['data' => $data]) ?>
            </div>
        </div>
    </div>
</div>

administrator/views/events/pending.php
<?php
$this->title = Yii::t('app', 'Event Awaiting Publication');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
            <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('success-message')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
        <?php endif; ?>
        <div class="panel panel-default">
            <div class="panel-heading">Events List</div>
            <div class="panel-body grid-font-formating">
                <?= $this->render('_data', ['data' => $data]) ?>
            </div>
        </div>
    </div>
</div>

administrator/views/events/publish.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Publish Event';
$this->params['breadcrumbs'][] = "Publish [" . $model->name . "]";
?>
<div class="site-login" style="margin-bottom: 50px;">
    <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
        <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
    <?php endif; ?>
    <?php if (Yii::$app->session->hasFlash('success-message')): ?>
        <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-12 text-right">
            <p style="border-bottom: 1px solid #f5f5f5; padding-bottom: 5px;">
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> Active Events List', ['active'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-success', 'title' => Yii::t('yii', 'Update Event'),]); ?>
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> Awaiting Publication List', ['pending'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-primary', 'title' => Yii::t('yii', 'Update Event'),]); ?>
                <?= Html::a('<span class="glyphicon glyphicon-list"></span> Events List', ['index'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-info', 'title' => Yii::t('yii', 'Update Event'),]); ?>
            </p>
        </div>
    </div>
    <div class="row" >
        <div id="login-container" style="float: none; ">
            <?php
            $form = ActiveForm::begin(['id' => 'publish-form']);
            if ($model->hasErrors()) {
                echo $form->errorSummary($model, ['header' => '']);
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'commission', ['inputOptions' => ['placeholder' => 'commision e.g 15.25']])->textInput(['autofocus' => true])->label() ?>
                </div>
            </div>
            <div class="form-group">
                <?= Html::submitButton('Publish Event', ['class' => 'btn btn-success', 'name' => 'login-button', 'style' => 'width:100%;']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

administrator/views/events/view.php
<?php
$this->title = Yii::t('app', 'Event');
$this->params['breadcrumbs'][] = $this->title;

use yii\helpers\Html;
?>

<div class="form-group mt10">
    <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
        <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
    <?php endif; ?>
    <?php if (Yii::$app->session->hasFlash('success-message')): ?>
        <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-12 text-right">
            <p>
                <?= Html::a('<span class="glyphicon glyphicon-ok"></span> Publish', ['publish', 'id' => $model->id], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-success', 'title' => Yii::t('yii', 'Publish Event'),]); ?>
                <?= Html::a('<span class="glyphicon glyphicon-remove"></span> Cancel', ['cancel', 'id' => $model->id], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-danger', 'title' => Yii::t('yii', 'Cancel Event'),]); ?>
            </p>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            Event Details
        </div>
        <div class="panel-body">
            <div class="row heading-row">
                <div class="col-md-3">
                    <label><b>Name : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Event Type: </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Country: </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>County: </b></label>
                </div>
            </div>     
            <div class="row details-row">
                <div class="col-md-3">
                    <?php echo Html::encode($model->name); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->eventTypeId['name']); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->countryId['name']); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->countyId['name']); ?>
                </div>
            </div>             
            <div class="row heading-row">
                <div class="col-md-3">
                    <label><b>Venue : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Location : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Latitude : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Longitude : </b></label>
                </div>
            </div>   
            <div class="row details-row">
                <div class="col-md-3">
                    <?php echo Html::encode($model->venue); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->location); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->latitude); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->longitude); ?>
                </div>
            </div>              
            <div class="row heading-row">
                <div class="col-md-3">
                    <label><b>Start Date : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Start Time : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>End Date : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>End Time : </b></label>
                </div>
            </div>   
            <div class="row details-row">
                <div class="col-md-3">
                    <?php echo Html::encode($model->startDate); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->startTime); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->endDate); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->endTime); ?>
                </div>
            </div>  
            <div class="row heading-row">
                <div class="col-md-6">
                    <label><b>Description : </b></label>
                </div>
                <div class="col-md-6">
                    <label><b>Poster : </b></label>
                </div>
            </div>  
            <div class="row details-row" style="padding-top: 5px;">
                <div class="col-md-6">
                    <?php echo Html::encode($model->description); ?>
                </div>
                <div class="col-md-6">
                    <?php $imgUrl = Yii::$app->params['merchantUrl'] . "/uploads/posters/$model->poster"; ?>
                    <?= Html::img($imgUrl, ['class' => 'img-responsive', 'style' => 'width:100%; height:200px;']) ?>
                </div>
            </div>    
        </div>
    </div>
    <?php if(count($tickettiers) > 0) : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Ticket Tiers
        </div>
        <div class="panel-body grid-font-formating">
            <?= $this->render('_tickets', ['tickets' => $tickettiers, 'visibility' => $visibility]) ?>
        </div>
    </div>  
    <?php endif; ?>
    <?php if(count($sponsors) > 0) : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Sponsors
        </div>
        <div class="panel-body" >
            <?php
            $i = 0;
            $items = count($sponsors);
            foreach ($sponsors as $data) {
                if ($i % 3 == 0) {
                    ?><div class="row"><?php
                }
                ?>
                    <div class="col-md-4 col-lg-4 main-card-holder"> 
                        <div class="row inner-image-card-row">
                            <div class="col-md-12  col-lg-12 image-card-holder">
                                <div class="row image-card-holder-row">
                                    <div class="col-md-12">
                                        <?php $imgUrl = Yii::$app->params['merchantUrl'] . "/uploads/sponsors/logo/$data->logo"; ?>
                                        <?= Html::img($imgUrl) ?>
                                    </div>
                                </div>
                                <div class="row details-card-holder-row">
                                    <div class="col-md-12">
                                        <h4><?= $data->name ?></h4>
                                        <p><?= $data->businessUrl ?></p>
                                        <hr/>
                                        <p><?= $data->itemSponsoring ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                    $i++;
                    if ($i % 3 == 0 || $i == $items) {
                        ?></div><?php
                }
            }
            ?>
        </div>
    </div>        
    <?php endif; ?>
    <?php if(count($gallery) > 0) : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Gallery
        </div>
        <div class="panel-body" >
            <?php
            $i = 0;
            $items = count($gallery);
            foreach ($gallery as $data) {
                if ($i % 3 == 0) {
                    ?><div class="row"><?php
                }
                ?>
                    <div class="col-md-4 col-lg-4 main-card-holder"> 
                        <div class="row inner-image-card-row">
                            <div class="col-md-12  col-lg-12 image-card-holder">
                                <div class="row image-card-holder-row">
                                    <div class="col-md-12">
                                        <?php $imgUrl = Yii::$app->params['merchantUrl'] . "/uploads/gallery/$data->photo"; ?>
                                        <?= Html::img($imgUrl) ?>
                                    </div>
                                </div>
                                <div class="row details-card-holder-row">
                                    <div class="col-md-12">
                                        <h4><?= $data->title ?></h4>
                                        <hr/>
                                        <p><?= $data->description ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                    $i++;
                    if ($i % 3 == 0 || $i == $items) {
                        ?></div><?php
                }
            }
            ?>
        </div>
    </div>  
    <?php endif; ?> 
</div>