merchants/controllers/EventsController.php
<?php

namespace merchants\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\Service;
use common\models\Events;
use yii\web\Response;
use yii\web\UploadedFile;
use common\models\EventTickets;
use common\models\EventSponsor;
use common\models\EventGallery;
use yii\helpers\Url;

/**
 * Site controller
 */
class EventsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $service = new Service();
        $data = $service->getMerchantEvents(1);
        $events = [];
        foreach ($data as $dt) {
            $model = new Events();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $events[] = $model;
        }
        return $this->render('index', ['data' => $events]);
    }

    public function actionPending() {
        $service = new Service();
        $data = $service->getMerchantEvents(7);
        $events = [];
        foreach ($data as $dt) {
            $model = new Events();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $events[] = $model;
        }
        return $this->render('pending', ['data' => $events]);
    }

    public function actionHistory() {
        $service = new Service();
        $data = $service->getMerchantEvents();
        $events = [];
        foreach ($data as $dt) {
            $model = new Events();
            $model->setAttributes($dt);
            $model->createdAt = $service->timestampToString1($model->createdAt);
            $events[] = $model;
        }
        return $this->render('history', ['data' => $events]);
    }

    public function actionCancel($id) {
        $service = new Service();
        $response = (Object) $service->deleteEvent($id);
        if ($response->status['code'] == 100) {
            \Yii::$app->getSession()->setFlash('success-message', "Event sucessfully cancelled.");
        } else {
            \Yii::$app->getSession()->setFlash('fail-message', $response->status['message']);
        }
        return $this->redirect(['index']);
    }

    public function actionAuthorize($id) {
        $service = new Service();
        $response = (Object) $service->authorizeEvent($id);
        if ($response->status['code'] == 100) {
            \Yii::$app->getSession()->setFlash('success-message', "Event sucessfully authorized.");
        } else {
            \Yii::$app->getSession()->setFlash('fail-message', $response->status['message']);
        }
        return $this->redirect(['view', 'id' => $id]);
    }

    public function actionCreate() {
        $service = new Service();
        $identity = Yii::$app->user->getIdentity();
        $model = new Events();
        $pendingEvent = $service->getPendingEvent();
        if (!empty($pendingEvent)) {
            foreach ($pendingEvent as $event) {
                $model->setAttributes($event);
            }
        }
        $eventSponsorModel = new EventSponsor();
        $eventGalleryModel = new EventGallery();
        $ticketModel = new EventTickets();
        $eventTypesData = $service->getEventTypes();
        $countryData = $service->getCountry();
        $countyData = $service->getCounty();
        $tickettypeData = $service->getTicketTypes();
        $ticketnameData = $service->getTicketNames(1);
        $ticketNames = $ticketTypes = $counties = $countries = $eventTypes = $eventTickets = $eventSponsors = $eventGalleries = [];
        if (!empty($model->id)) {
            $eventTicketsData = $service->getEventTicketTiers($model->id, 1);
            foreach ($eventTicketsData as $eventTicket) {
                $ticketsModel = new EventTickets();
                $ticketsModel->setAttributes($eventTicket);
                $eventTickets[] = $ticketsModel;
            }
            $eventGalleryData = $service->getEventGalleries($model->id, $identity->merchantId['id'], 1);
            foreach ($eventGalleryData as $data) {
                $dataModel = new EventGallery();
                $dataModel->setAttributes($data);
                $eventGalleries[] = $dataModel;
            }
            $eventSponsorData = $service->getEventSponsors($model->id, $identity->merchantId['id'], 1);
            foreach ($eventSponsorData as $data) {
                $dataModel = new EventSponsor();
                $dataModel->setAttributes($data);
                $eventSponsors[] = $dataModel;
            }
        }
        foreach ($eventTypesData as $data) {
            $eventTypes[$data['id']] = $data['name'];
        }
        foreach ($countyData as $data) {
            $counties[$data['id']] = $data['name'];
        }
        foreach ($countryData as $data) {
            $countries[$data['id']] = $data['name'];
        }
        $ticketNames[] = "Select Ticket Name";
        foreach ($ticketnameData as $data) {
            $ticketNames[$data['id']] = $data['name'];
        }
        $ticketTypes[] = "Select Ticket Type";
        foreach ($tickettypeData as $data) {
            $ticketTypes[$data['id']] = $data['name'];
        }
        return $this->render('create', [
                    'model' => $model,
                    'eventTypes' => $eventTypes,
                    'countries' => $countries,
                    'counties' => $counties,
                    'ticketModel' => $ticketModel,
                    'ticketNames' => $ticketNames,
                    'ticketTypes' => $ticketTypes,
                    'eventTickets' => $eventTickets,
                    'eventSponsorModel' => $eventSponsorModel,
                    'eventGalleryModel' => $eventGalleryModel,
                    'eventGalleries' => $eventGalleries,
                    'eventSponsors' => $eventSponsors
        ]);
    }

    public function actionUpdate($id) {
        $model = new Events();
        $eventSponsorModel = new EventSponsor();
        $eventGalleryModel = new EventGallery();
        $service = new Service();
        $identity = Yii::$app->user->getIdentity();
        $eventDetails = $service->getEventDetails($id);
        $eventTickets = $eventGalleries = $eventSponsors = [];
        $model->setAttributes($eventDetails['event']);
        foreach ($eventDetails['tickets'] as $eventTicket) {
            $ticketsModel = new EventTickets();
            $ticketsModel->setAttributes($eventTicket);
            $eventTickets[] = $ticketsModel;
        }

        $eventGalleryData = $service->getEventGalleries($model->id, $identity->merchantId['id'], 1);
        foreach ($eventGalleryData as $data) {
            $dataModel = new EventGallery();
            $dataModel->setAttributes($data);
            $eventGalleries[] = $dataModel;
        }
        $eventSponsorData = $service->getEventSponsors($model->id, $identity->merchantId['id'], 1);
        foreach ($eventSponsorData as $data) {
            $dataModel = new EventSponsor();
            $dataModel->setAttributes($data);
            $eventSponsors[] = $dataModel;
        }

        $ticketModel = new EventTickets();
        $eventTypesData = $service->getEventTypes();
        $countryData = $service->getCountry();
        $countyData = $service->getCounty();
        $tickettypeData = $service->getTicketTypes();
        $ticketnameData = $service->getTicketNames(1);
        $ticketNames = $ticketTypes = $counties = $countries = $eventTypes = [];

        foreach ($eventTypesData as $data) {
            $eventTypes[$data['id']] = $data['name'];
        }
        foreach ($countyData as $data) {
            $counties[$data['id']] = $data['name'];
        }
        foreach ($countryData as $data) {
            $countries[$data['id']] = $data['name'];
        }
        $ticketNames[] = "Select Ticket Name";
        foreach ($ticketnameData as $data) {
            $ticketNames[$data['id']] = $data['name'];
        }
        $ticketTypes[] = "Select Ticket Type";
        foreach ($tickettypeData as $data) {
            $ticketTypes[$data['id']] = $data['name'];
        }
        return $this->render('update', [
                    'model' => $model,
                    'eventTypes' => $eventTypes,
                    'countries' => $countries,
                    'counties' => $counties,
                    'ticketModel' => $ticketModel,
                    'ticketNames' => $ticketNames,
                    'ticketTypes' => $ticketTypes,
                    'eventTickets' => $eventTickets,
                    'eventSponsorModel' => $eventSponsorModel,
                    'eventGalleryModel' => $eventGalleryModel,
                    'eventGalleries' => $eventGalleries,
                    'eventSponsors' => $eventSponsors
        ]);
    }

    public function actionDetails() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $service = new Service();
        $model = new Events();
        $model->load(Yii::$app->request->post());

        $poster = UploadedFile::getInstance($model, 'poster');
        if ($poster) {
            $name = $poster->name;
            $path = Yii::getAlias('@webroot') . '/uploads/posters/' . $name;
            $poster->saveAs($path);
            $model->poster = $name;
        } else {
            if (!empty($model->id)) {
                $modelData = new Events();
                $modelData->setAttributes($service->getSingleEvent($model->id));

merchants/views/events/_data.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
?>
<?=
GridView::widget([
    'dataProvider' => new ArrayDataProvider([ 'allModels' => $data]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label'=>'Event Name',
            'value'=>function($data){
                return $data->name;
            }
        ],
        [
            'label'=>'Start Date',
            'value'=>function($data){
                return $data->startDate;
            }
        ],
        [
            'label'=>'Start Time',
            'value'=>function($data){
                return $data->startTime;
            }
        ],
        [
            'label'=>'End Date',
            'value'=>function($data){
                return $data->endDate;
            }
        ],
        [
            'label'=>'End Time',
            'value'=>function($data){
                return $data->endTime;
            }
        ],
        [
            'label'=>'Status',
            'value'=>function($data){
                return $data->statusId['name'];
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}&nbsp;&nbsp;{delete}&nbsp;&nbsp;{authorize}&nbsp;&nbsp;',
            'buttons' => [
                'view' => function($url, $model) {
                    $url = Url::toRoute(['events/view', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, ['title' => Yii::t('yii', 'View'),]);
                },
                'delete' => function($url, $model) {
                    $url = Url::toRoute(['events/cancel', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, ['title' => Yii::t('yii', 'Cancel'),]);
                },
                'authorize' => function($url, $model) {
                    $url = Url::toRoute(['events/authorize', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-ok"></span>', $url, ['title' => Yii::t('yii', 'Authorize'), 'class'=>$model->statusId['id'] == 7 ? "disable-merchant-verification" : "enable-merchant-verification"]);
                },
                    ],
                ],
            ],
        ]);
        ?>

merchants/views/events/_eventgallery.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
?>
<?php
$form = ActiveForm::begin([
            'action' => Yii::$app->urlManager->createUrl(['events/create-event-gallery']),
            'id' => 'event-gallery-form',
            'enableClientValidation' => true,
        ]);
?>                
<?= Html::activeHiddenInput($model, 'id') ?>
<?= Html::activeHiddenInput($model, 'eventId') ?>
<?= Html::activeHiddenInput($model, 'merchantId') ?>
<div class="row">
    <div class="col-md-12">     
        <div class="row">
            <div class="col-md-6">
                <?=
                $form->field($model, 'title', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-bookmark"></span>']], 
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textInput()
                ?>
            </div>
            <div class="col-md-6">              
                <?=
                $form->field($model, 'photo', [
                    'options' => ['accept' => 'image/*'],
                ])->fileInput();
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?=
                $form->field($model, 'description', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-tasks"></span>']], 
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textarea(['rows' => 3])
                ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<h2></h2>
<div class="alert alert-danger"  id="error-summary" style="display: none;"></div>
<h2></h2>
<div id="progress-spinner" class="text-center" style="display: none;">
    <?= Html::img('@web/images/ajax-loader.gif', ['alt' => 'progress spinner']) ?>
</div>
<h2></h2>

merchants/views/events/_eventsForm.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use kartik\date\DatePicker;
use kartik\time\TimePicker;
use kartik\widgets\Select2;
?>
<?php
$form = ActiveForm::begin([
            'action' => Yii::$app->urlManager->createUrl(['events/details']),
            'id' => 'events-details-form',
            'enableClientValidation' => true,
        ]);
?>
<?= Html::activeHiddenInput($model, 'id') ?>
<div class="row">
    <div class="col-md-12">        
        <div class="row">
            <div class="col-md-4">
                <?=
                $form->field($model, 'name', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-th"></span>']], 'inputOptions' => ['class' => 'form-control  form-control-custom'],])->textInput()
                ?>
            </div>
            <div class="col-md-4"><?=
                $form->field($model, 'eventTypeId')->widget(Select2::classname(), [
                    'data' => $eventTypes,
                    'options' => ['placeholder' => 'Select Event Type ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>
            </div>
            <div class="col-md-4">                
                <?=
                $form->field($model, 'poster', [
                    'options' => ['accept' => 'image/*'],
                ])->fileInput();
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">    
                <?=
                $form->field($model, 'location', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-globe"></span>']], 'inputOptions' => ['class' => 'form-control  form-control-custom'],])->textInput()
                ?>
            </div>
            <div class="col-md-6">
                <?=
                $form->field($model, 'venue', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-globe"></span>']], 'inputOptions' => ['class' => 'form-control  form-control-custom'],])->textInput()
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">    
                <?=
                $form->field($model, 'latitude', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-map-marker"></span>']], 'inputOptions' => ['class' => 'form-control  form-control-custom'],])->textInput()
                ?>
            </div>
            <div class="col-md-3">
                <?=
                $form->field($model, 'longitude', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-map-marker"></span>']], 'inputOptions' => ['class' => 'form-control  form-control-custom'],])->textInput()
                ?>
            </div><div class="col-md-3">   <?=
                $form->field($model, 'countryId')->widget(Select2::classname(), [
                    'data' => $countries,
                    'options' => ['placeholder' => 'Select country ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>
            </div>
            <div class="col-md-3"><?=
                $form->field($model, 'countyId')->widget(Select2::classname(), [
                    'data' => $counties,
                    'options' => ['placeholder' => 'Select county ...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">                
                <?=
                $form->field($model, 'startDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true,
                    ]
                ])
                ?>
            </div>
            <div class="col-md-6">            
                <?=
                $form->field($model, 'startTime', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(TimePicker::classname(), [
                    'value' => date("hh:mm"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'hh:mm',
                        'showMeridian' => false,
                        'minuteStep' => 5,
                    ]
                ])
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">                
                <?=
                $form->field($model, 'endDate', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(DatePicker::classname(), [
                    'value' => date("Y-m-d"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'yyyy-mm-dd',
                        'todayHighlight' => true,
                    ]
                ])
                ?>
            </div>
            <div class="col-md-6">            
                <?=
                $form->field($model, 'endTime', [
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->widget(TimePicker::classname(), [
                    'value' => date("hh:mm"),
                    'pluginOptions' => [
                        'autoclose' => true,
                        'format' => 'hh:mm',
                        'showMeridian' => false,
                        'minuteStep' => 5,
                    ]
                ])
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <?= $form->field($model, 'description', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-list"></span>']], 'inputOptions' => ['class' => 'form-control  form-control-custom'],])->textarea(['rows' => 7]) ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

merchants/views/events/_eventsponsors.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
?>
<?php
$form = ActiveForm::begin([
            'action' => Yii::$app->urlManager->createUrl(['events/create-event-sponsor']),
            'id' => 'event-sponsor-form',
            'enableClientValidation' => true,
        ]);
?>                
<?= Html::activeHiddenInput($model, 'id') ?>
<?= Html::activeHiddenInput($model, 'eventId') ?>
<?= Html::activeHiddenInput($model, 'merchantId') ?>
<div class="row">
    <div class="col-md-12">     
        <div class="row">
            <div class="col-md-6">
                <?=
                $form->field($model, 'name', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-bookmark"></span>']], 
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textInput()
                ?>
            </div>
            <div class="col-md-6">
                <?=
                $form->field($model, 'itemSponsoring', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-tasks"></span>']], 
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textInput()
                ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7">
                <?=
                $form->field($model, 'businessUrl', ['addon' => ['prepend' => ['content' => '<span>www.example.com</span>']], 
                    'inputOptions' => ['class' => 'form-control  form-control-custom'],
                ])->textInput()
                ?>
            </div>
            <div class="col-md-5">              
                <?=
                $form->field($model, 'logo', [
                    'options' => ['accept' => 'image/*'],
                ])->fileInput();
                ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<h2></h2>
<div class="alert alert-danger"  id="error-summary" style="display: none;"></div>
<h2></h2>
<div id="progress-spinner" class="text-center" style="display: none;">
    <?= Html::img('@web/images/ajax-loader.gif', ['alt' => 'progress spinner']) ?>
</div>
<h2></h2>

merchants/views/events/_finish.php
<?php

use yii\helpers\Html;
?>
<div class="form-group">
    <div class="alert alert-danger"  id='finish-error-summary' role="alert" style="display: none;"> </div>
</div>
<div class="form-group mt10">
    <div class="panel panel-default">
        <div class="panel-heading">
            Event Details
        </div>
        <div class="panel-body">
            <div class="row heading-row">
                <div class="col-md-3">
                    <label><b>Name : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Event Type: </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Country: </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>County: </b></label>
                </div>
            </div>     
            <div class="row details-row">
                <div class="col-md-3">
                    <?php echo Html::encode($model->name); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->eventTypeId['name']); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->countryId['name']); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->countyId['name']); ?>
                </div>
            </div>             
            <div class="row heading-row">
                <div class="col-md-3">
                    <label><b>Venue : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Location : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Latitude : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Longitude : </b></label>
                </div>
            </div>   
            <div class="row details-row">
                <div class="col-md-3">
                    <?php echo Html::encode($model->venue); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->location); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->latitude); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->longitude); ?>
                </div>
            </div>              
            <div class="row heading-row">
                <div class="col-md-3">
                    <label><b>Start Date : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>Start Time : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>End Date : </b></label>
                </div>
                <div class="col-md-3">
                    <label><b>End Time : </b></label>
                </div>
            </div>   
            <div class="row details-row">
                <div class="col-md-3">
                    <?php echo Html::encode($model->startDate); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->startTime); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->endDate); ?>
                </div>
                <div class="col-md-3">
                    <?php echo Html::encode($model->endTime); ?>
                </div>
            </div>  
            <div class="row heading-row">
                <div class="col-md-6">
                    <label><b>Description : </b></label>
                </div>
                <div class="col-md-6">
                    <label><b>Poster : </b></label>
                </div>
            </div>  
            <div class="row details-row" style="padding-top: 5px;">
                <div class="col-md-6">
                    <?php echo Html::encode($model->description); ?>
                </div>
                <div class="col-md-6">
                    <?= Html::img("@web/uploads/posters/$model->poster", ['class' => 'img-responsive', 'style' => 'width:300px; height:200px;']) ?>
                </div>
            </div>    
        </div>
    </div>
    <?php if(count($tickettiers) > 0) : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Ticket Tiers
        </div>
        <div class="panel-body grid-font-formating" >
            <?= $this->render('_tickets', ['tickets' => $tickettiers, 'visibility' => $visibility]) ?>
        </div>
    </div> 
    <?php endif; ?>
    <?php if(count($sponsors) > 0) : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Sponsors
        </div>
        <div class="panel-body" >
            <?php
            $i = 0;
            $items = count($sponsors);
            foreach ($sponsors as $data) {
                if ($i % 3 == 0) {
                    ?><div class="row"><?php
                }
                ?>
                <div class="col-md-4 col-lg-4 main-card-holder"> 
                    <div class="row inner-image-card-row">
                        <div class="col-md-12  col-lg-12 image-card-holder">
                            <div class="row image-card-holder-row">
                                <div class="col-md-12">
                                    <?= Html::img("@web/uploads/sponsors/logo/$data->logo", ['class' => 'img-responsive']) ?>
                                </div>
                            </div>
                            <div class="row details-card-holder-row">
                                <div class="col-md-12">
                                    <h4><?= $data->name ?></h4>
                                    <p><?= $data->businessUrl ?></p>
                                    <hr/>
                                    <p><?= $data->itemSponsoring ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
                $i++;
                if ($i % 3 == 0 || $i == $items) {
                    ?></div><?php
                }
            }
            ?>
        </div>
    </div>    
    <?php endif; ?>
    <?php if(count($gallery) > 0) : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            Gallery
        </div>
        <div class="panel-body" >
            <?php
            $i = 0;
            $items = count($gallery);
            foreach ($gallery as $data) {
                if ($i % 3 == 0) {
                    ?><div class="row"><?php
                }
                ?>
                <div class="col-md-4 col-lg-4 main-card-holder"> 
                    <div class="row inner-image-card-row">
                        <div class="col-md-12  col-lg-12 image-card-holder">
                            <div class="row image-card-holder-row">
                                <div class="col-md-12">
                                    <?= Html::img("@web/uploads/gallery/$data->photo", ['class' => 'img-responsive']) ?>
                                </div>
                            </div>
                            <div class="row details-card-holder-row">
                                <div class="col-md-12">
                                    <h4><?= $data->title ?></h4>
                                    <hr/>
                                    <p><?= $data->description ?></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
                $i++;
                if ($i % 3 == 0 || $i == $items) {
                    ?></div><?php
                }
            }
            ?>
        </div>
    </div>   
    <?php endif; ?>
</div>