merchants/controllers/UsersController.php
<?php

namespace merchants\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use common\models\Service;
use common\models\UserAccount;

/**
 * Site controller
 */
class UsersController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $service = new Service();
        $identity = Yii::$app->user->getIdentity();
        $usersData = $service->getAllUsers($identity->merchantId['id'],1);
        $users = [];
        foreach ($usersData as $data) {
            if($identity->id == $data['id']){
                continue;
            }
            $user = new UserAccount();
            $user->setAttributes($data);
            $users[] = $user;
        }
        return $this->render('index', ['users' => $users]);
    }

    public function actionRecycle() {
        $service = new Service();
        $identity = Yii::$app->user->getIdentity();
        $usersData = $service->getAllUsers($identity->merchantId['id'],8);
        $users = [];
        foreach ($usersData as $data) {
            if($identity->id == $data['id']){
                continue;
            }
            $user = new UserAccount();
            $user->setAttributes($data);
            $users[] = $user;
        }
        return $this->render('index', ['users' => $users]);
    }

    public function actionCreate() {
        $model = new UserAccount();
        if ($model->load(Yii::$app->request->post())) {
            $model->password = $model->phoneNumber;
            $model->confirmPassword = $model->phoneNumber;
            $model->userRolesId = 3;
            $model->userTypesId = 2;
            if ($model->validate()) {
                $identity = Yii::$app->user->getIdentity();
                $model->merchantId = $identity->merchantId['id'];
                $service = new Service();
                $response = (Object) $service->createUserAccount($model);
                if ($response->status['code'] == 100) {
                    \Yii::$app->getSession()->setFlash('success-message', "User account sucessfully created. Check user email for activation details");
                    return $this->redirect(['index']);
                } else {
                    $model->addError("", $response->status['message']);
                }
            }
        }
        return $this->render('create', ['model' => $model]);
    }

    public function actionDelete($id) {
        $service = new Service();
        $response = (Object) $service->deleteUser($id);
        if ($response->status['code'] == 100) {
            \Yii::$app->getSession()->setFlash('success-message', "User account sucessfully deleted.");
        } else {
            \Yii::$app->getSession()->setFlash('fail-message', $response->status['message']);
        }
        return $this->redirect(['index']);
    }

}

merchants/views/users/_data.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\helpers\Url;
?>
<?=
GridView::widget([
    'dataProvider' => new ArrayDataProvider([ 'allModels' => $data]),
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label'=>'Name',
            'value'=>function($data){
                return $data->name;
            }
        ],
        [
            'label'=>'Username',
            'value'=>function($data){
                return $data->email;
            }
        ],
        [
            'label'=>'Last Login',
            'value'=>function($data){
                return $data->lastLogin;
            }
        ],
        [
            'label'=>'Status',
            'value'=>function($data){
                return $data->statusId['name'];
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{delete}&nbsp;&nbsp;',
            'buttons' => [
                'delete' => function($url, $model) {
                    $url = Url::toRoute(['users/delete', 'id' => $model->id]);
                    return Html::a('<span class="glyphicon glyphicon-remove"></span>', $url, ['title' => Yii::t('yii', 'Delete'),]);
                },
                    ],
                ],
            ],
        ]);
        ?>

merchants/views/users/create.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use kartik\form\ActiveForm;

$this->title = 'Account Creation';
$this->params['breadc rumbs'][] = $this->title;
?>
<div class="site-login" style="margin-bottom: 50px;">
    <div class="panel panel-default">
        <div class="panel-heading"><?= $this->title ?></div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <?php
                    $form = ActiveForm::begin(['id' => 'account-creation-form']);
                    if ($model->hasErrors()) {
                        echo $form->errorSummary($model, ['header' => '']);
                    }
                    ?>
                    <div class="row">
                        <div class="col-md-4">
                            <?= $form->field($model, 'name', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-user"></span>']], 'inputOptions' => ['placeholder' => 'Name']])->textInput()->label() ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <?= $form->field($model, 'email', ['addon' => ['prepend' => ['content' => '@']], 'inputOptions' => ['placeholder' => 'Email']])->textInput()->label() ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <?= $form->field($model, 'phoneNumber', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-phone"></span>']], 'inputOptions' => ['placeholder' => 'Phone Number']])->textInput()->label() ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?= Html::submitButton('Create Account', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

merchants/views/users/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

merchants/views/users/index.php
<?php
use yii\helpers\Html;

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row members-index">
    <div class="col-md-12">
        <?php if (Yii::$app->session->hasFlash('fail-message')): ?>
            <div class="alert alert-danger"><?= Yii::$app->session->getFlash('fail-message') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('success-message')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success-message') ?></div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-12 text-right">
                <p><?= Html::a('<span class="glyphicon glyphicon-plus"></span> Add User', ['create'], ['style' => 'margin-right:10px;', 'class' => 'btn btn-sm btn-primary', 'title' => Yii::t('yii', 'Add User'),]); ?></p>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><?= $this->title ?></div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <?= $this->render('_data', ['data' => $users]) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

merchants/views/users/requestPasswordReset.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use kartik\form\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="row signup-main-row">
        <div class="col-lg-1"></div>
        <div class="col-lg-4">
            <?php
                $form = ActiveForm::begin(['id' => 'request-password-reset-form']);

                if ($model->hasErrors()) {
                    echo $form->errorSummary($model, ['header' => '']);
                }
            ?>

            <?= $form->field($model, 'username', ['addon' => ['prepend' => ['content' => '<span class="glyphicon glyphicon-user"></span>']], 'inputOptions' => ['placeholder' => 'username']])->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Request Reset', ['class' => 'btn btn-primary', 'style' => 'border-radius:0px;',]) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>